name: Promote Country Data TEST

on:
  workflow_dispatch:
    inputs:
      country:
        description: "Country to promote"
        required: true
        type: string
      lable_period_name:
        description: "Lable period to promote"
        required: true
        type: string				
											  
					  
					

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Databricks Job
        run: |
          curl -X POST \
          ${{ secrets.DATABRICKS_HOST }}/api/2.1/jobs/run-now \
          -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
                "job_id": 199210744483597,
                "notebook_params": {
                  "country": "${{ github.event.inputs.country }}"
                }
              }'
